auto_start: true
created_at: '2025-09-03T17:58:44.266231'
description: "\u6F14\u793A\u7528\u7684 Nginx \u670D\u52A1\u5668"
docker_command: docker run -d -p 8080:80 --name demo-nginx nginx:latest
environment:
  ENV: production
  NGINX_WORKER_PROCESSES: '4'
health_check:
  interval: 30000000000
  retries: 3
  test:
  - CMD
  - curl
  - -f
  - http://localhost/health
  timeout: 10000000000
host: localhost
labels:
  app: web-server
  managed-by: msm
  version: '1.0'
name: demo-nginx-server
networks:
- bridge
- app-network
port: 8080
restart_policy: always
updated_at: '2025-09-03T17:58:44.266244'
volumes:
- /host/logs:/var/log/nginx
- /host/config:/etc/nginx/conf.d
