auto_start: true
created_at: '2025-09-04T10:47:55.939133'
description: 演示用的 Nginx 服务器
docker_command: docker run -d -p 8080:80 --name demo-nginx nginx:latest
environment:
  ENV: production
  NGINX_WORKER_PROCESSES: '4'
health_check:
  interval: 30000000000
  retries: 3
  test:
  - CMD
  - curl
  - -f
  - http://localhost/health
  timeout: 10000000000
host: localhost
labels:
  app: web-server
  managed-by: msm
  version: '1.0'
name: demo-nginx-server
networks:
- bridge
- app-network
port: 8080
restart_policy: always
updated_at: '2025-09-04T10:47:55.939143'
volumes:
- /host/logs:/var/log/nginx
- /host/config:/etc/nginx/conf.d
